### ISSUE TITLE
Upgrade to TS 4.0

### ISSUE THREAD

**Issue by diberry** [microsoft/TypeScript-Node-Starter#305]
4.0 is released, can we move to that - maybe some refactoring?

**Comment by bluepuma77** [comment]
Please Microsoft, it would be great to have a a working TypeScript starter kit.

Let the fun begin:
```
git clone https://github.com/microsoft/TypeScript-Node-Starter
cd TypeScript-Node-Starter
npm install
npm --depth 10 update
npm run build
```
Not so fun result: **Found 165 errors.**

**Comment by diberry** [comment]
@peterblazejewicz @orta Can we expand the admin list (I volunteer) for this repo so interested parties can help maintain? Or are you looking for abandon/start over?

**Comment by orta** [comment]
I'm not against having more admins (I've added you either way) but I'm _generally_ not sold on this repo as being a useful learning device. It's more like a relic from the days when TypeScript had to prove it could work with node, and not from the more modern era when pretty much any web framework works with TS out of the box.

Which is why I ended up describing it like this in the repo:

>It is not a goal to be a comprehensive and definitive guide to making a TypeScript and Node project, but as a working reference maintained by the community. 

There's some value in the repo as a 'here's how pieces can come together', but there are many well maintained [community bootstrapping projects](https://www.typescriptlang.org/docs/bootstrap) which do a much better job of documenting and encapsulating the complexity in building a node web app. So, I've left it mainly to the community to maintain and not archived it.

I'm pretty open to being swayed in different directions though 👍🏻

**Comment by diberry** [comment]
@Orta - at first glance - I don't see an express project in the list. If you were to recommend an Express replacement, moving into the modern era, what would that be?

**Comment by orta** [comment]
Express is still a solid choice, but it doesn't come with a typescript template or docs etc - so it didn't make the list.

Fastify is closest to express (and what I used last) but Nest/Feathers/LoopBack all seem like good options for a more batteries-included style framework.

**Comment by peterblazejewicz** [comment]
Let me look into this, not having a proper laptop this times :)
