### ISSUE TITLE
[question] Is this a good starter for a Node API, or would it be over-complex?

### ISSUE THREAD

**Issue by QuantumInformation** [Microsoft/TypeScript-Node-Starter#57]

**Comment by bowdenk7** [comment]
There are probably better starting points out there, but really you would just need to delete things from this starter. The biggest difference is that in each controller, instead of calling `res.render` and returning a page, you would just want to return `json`. You can easily do this using `res.json`.

Link: http://expressjs.com/en/api.html#res.json
