### ISSUE TITLE
[Question] Deployment of dist folder in production

### ISSUE THREAD

**Issue by aneem** [Microsoft/TypeScript-Node-Starter#97]
I am using this repo for a api-based nodejs based application, so I'd basically be returning json objects from the application. 

The **npm build** command generates a dist folder with compiled javascript files and the **npm serve** commands make use of the server.js from the dist folder.
While development, I am using nodemon and ts-node to compile typescript files on the fly, but do I use it in production enviroment?

How do i deploy the application? Do I have to copy the package.json into the dist folder, copy the contents of dist folder to server location, then do a npm install? Or do I use the entire project itself and use typescript in the deployment environment as well?

**Comment by welkie** [comment]
Since this starter is set up in a way that puts the compiled JS files in a distinct directory, I find the simplest way to use this is to skip ts-node. I simply run the compiled JS in production. If preparing a Docker image, I would delete the source code files after the compile step to minimize the image size.

In order to get stack traces in production that would provide meaningful information, matching the TS lines that threw the errors, I would keep the source maps and use a tool like [https://github.com/evanw/node-source-map-support](node-source-map-support). You use it by requiring it at the top of your entry point source code file for its side effects.

**Comment by aneem** [comment]
Thanks very much for your overview @welkie . I'll be sure to implement https://github.com/evanw/node-source-map-support in my project.
